Require flake8 < 5 to avoid config error
If you use flake8 5.x, you get this error:

AttributeError: module 'flake8.options.config' has no attribute 'ConfigFileFinder'

On the GitHub issue tracker for pytest-flake8, other people report
this error too, and currently there is no fix other than don't use
version 5 of flake8.